version = 0.1

[default.deploy.parameters]
stack_name = "london-flight-map"
region = "eu-west-2"
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
disable_rollback = false
resolve_s3 = true
parameter_overrides = "EpcApiKey=''"
profile = "flightmap"
