"""The Bay Area on the LIVE map, from the files the /bay-area/ page is built from.

    python scripts/build_bayarea_map_data.py --check   # re-derive, compare both holders (blocking)
    python scripts/build_bayarea_map_data.py --write

Release 1 of the Bay Area on the map (ROADMAP "The Bay Area flight-path page",
the live-map checklist). Ruled 2026-10-05 (Bill): a Bay Area city shows the
/bay-area/ page's FACTS, with no number, because every UK quiet estimate is
fitted against DEFRA's measurements and the Bay Area has no yardstick; the
ranking is the page's own order, by share of the city on the federal noise map.

Two holders, both written here so they cannot disagree with the page:

1. data/us-bayarea-cities.json - the 50 cities' outlines, each carrying the
   page's own text for its row (computed by build_bay_area_page.facts() and
   its cell functions, so the wording is the page's, not a second copy).
   The live map draws every city through d3's SPHERICAL paths; the preview
   gets away with drawing these outlines on the plane. Census shapefile rings
   wind as d3 wants for an outer ring (clockwise) and a hole (anticlockwise),
   but data/us-bayarea-places.json keeps each place as a flat list of rings,
   and drawn one polygon per ring a hole becomes the whole globe less the
   hole: the map is painted solid. So the rings are GROUPED here, each hole
   under the outer ring that contains it, and the grouping is checked rather
   than assumed.
   NOT named `*-boroughs.json`: that suffix is globbed by five scripts to
   enumerate the UK cities, two of which would then ask DEFRA and the
   Environment Agency for California (CLAUDE.md).

2. index.html, between BAYAREA-MAP markers - the three airports and the lines
   the page draws, in the frontend dialect (`coordinates`, [lon, lat]). The
   page's routes() is the one geometry: its own comment records what drawing
   a different line from the one measured cost ("six cities had a line across
   them and 'No' in their row"), so the map draws exactly what the facts were
   measured against.
"""

import argparse
import html
import json
import math
import sys
from collections import Counter
from pathlib import Path

import build_bay_area_page as page
import build_flight_paths as uk

ROOT = Path(__file__).resolve().parents[1]
PLACES = ROOT / 'data' / 'us-bayarea-places.json'
RECORD = ROOT / 'data' / 'us-flight-procedures.json'
OUT = ROOT / 'data' / 'us-bayarea-cities.json'
ROUTES_OUT = ROOT / 'data' / 'us-bayarea-routes.json'  # the front page's lines (route_records)
SITE = ROOT / 'index.html'
START = '// BAYAREA-MAP:START (generated by scripts/build_bayarea_map_data.py --write; do not hand-edit)'
END = '// BAYAREA-MAP:END'

# The four counties that hold SFO, OAK and SJC, and how many incorporated
# cities and towns each holds (EXPANSION.md "Which cities"). Asserted, so a
# place file that lost a county or gained the unincorporated communities
# cannot pass as the same map.
COUNTY_CITIES = {'San Francisco': 1, 'San Mateo': 20, 'Santa Clara': 15, 'Alameda': 14}
STEP_KM = 1.0  # every corridor the live map draws is on a 1 km interval (CLAUDE.md)


def signed_area(ring):
    """Shoelace area in degrees squared: positive anticlockwise, negative clockwise."""
    return (
        sum(
            ring[i][0] * ring[(i + 1) % len(ring)][1] - ring[(i + 1) % len(ring)][0] * ring[i][1]
            for i in range(len(ring))
        )
        / 2
    )


def inside(pt, ring):
    """Ray casting; the point is a hole's first vertex, never on the outer ring."""
    x, y = pt
    hit = False
    for i in range(len(ring)):
        (x1, y1), (x2, y2) = ring[i], ring[i - 1]
        if (y1 > y) != (y2 > y) and x < (x2 - x1) * (y - y1) / (y2 - y1) + x1:
            hit = not hit
    return hit


def polygons(place):
    """[[outer, hole, ...], ...] with each hole under the outer ring that contains it."""
    outers = [r for r in place['rings'] if signed_area(r) < 0]
    holes = [r for r in place['rings'] if signed_area(r) > 0]
    if not outers:
        raise SystemExit(f"{place['name']}: no clockwise ring, so no outer ring: the winding is not the Census's")
    polys = [[o] for o in outers]
    for h in holes:
        # The smallest outer ring holding it, for a hole inside an island inside a hole.
        holders = [p for p in polys if inside(h[0], p[0])]
        if not holders:
            raise SystemExit(f'{place["name"]}: an anticlockwise ring lies inside no outer ring')
        min(holders, key=lambda p: abs(signed_area(p[0]))).append(h)
    return polys


# Only what the /bay-area/ page's own map shows. San Francisco's outline holds the
# Farallon Islands, 45 km out to sea; drawn, they would sit outside the map box
# at every width (tests/map-fit.mjs), and the page frames each place on its
# largest ring for the same reason. A dropped polygon is reported, and only San
# Francisco is expected to lose one.
EXPECTED_OFFSHORE = {'San Francisco': 1}


def in_frame(polys, frame_box):
    w, s, e, n = frame_box
    kept = [p for p in polys if any(w <= x <= e and s <= y <= n for x, y in p[0])]
    return kept, len(polys) - len(kept)


def row_facts(c, rank):
    """The page's own words for one city's row, unescaped: the map escapes on render."""
    return {
        'rank': rank,
        'noise': html.unescape(page.noise_cell(c)),
        'noise_pct': round(c['noise_pct'], 1),
        'noise_from': html.unescape(page.airfield_cell(c)),
        'approach': html.unescape(page.approach_cell(c)),
        'arrival': html.unescape(page.arrival_cell(c)),
        'departure': html.unescape(page.departure_cell(c)),
        'nearest_route': html.unescape(page.nearest_cell(c)),
    }


def build():
    data = json.loads(PLACES.read_text(encoding='utf-8'))
    record = json.loads(RECORD.read_text(encoding='utf-8'))
    cities = [p for p in data['places'] if p['kind'] != 'cdp']
    counts = Counter(p['county'] for p in cities)
    if dict(counts) != COUNTY_CITIES:
        raise SystemExit(f'cities per county {dict(counts)}, expected {COUNTY_CITIES}')
    f = page.facts(data, record)
    rows = {c['name']: row_facts(c, rank) for rank, c in enumerate(page.order(f['cities']), 1)}
    frame = page.Frame(data['frame']['px'])
    west, north = page.lonlat_of(frame.x0, frame.y0)
    east, south = page.lonlat_of(frame.x1, frame.y1)
    shapes, dropped = {}, {}
    for p in cities:
        shapes[p['name']], gone = in_frame(polygons(p), (west, south, east, north))
        if gone:
            dropped[p['name']] = gone
    if dropped != EXPECTED_OFFSHORE:
        raise SystemExit(f'polygons outside the page frame {dropped}, expected {EXPECTED_OFFSHORE}')
    if set(rows) != {p['name'] for p in cities}:
        raise SystemExit("the page's rows and the outlines name different cities")
    fc = {
        'type': 'FeatureCollection',
        'source': data['source'],
        'vintage': data['vintage'],
        'routes': f'FAA CIFP cycle {record["cycle"]}, effective {record["effective"]}',
        'generator': 'scripts/build_bayarea_map_data.py --write, from data/us-bayarea-places.json',
        'features': [
            {
                'type': 'Feature',
                'properties': {
                    'name': p['name'],
                    'county': p['county'],
                    'geoid': p['geoid'],
                    'kind': p['kind'],
                    **rows[p['name']],
                },
                'geometry': {'type': 'MultiPolygon', 'coordinates': shapes[p['name']]},
            }
            for p in sorted(cities, key=lambda p: p['name'])
        ],
    }
    return fc, f, record


def every_km(line):
    """(lat, lon) points at no more than STEP_KM apart, ends kept."""
    out = [line[0]]
    for (la1, lo1), (la2, lo2) in zip(line, line[1:], strict=False):
        km = math.hypot((lo2 - lo1) * 111.32 * math.cos(math.radians(la1)), (la2 - la1) * 111.19)
        n = max(1, math.ceil(km / STEP_KM))
        out += [(la1 + (la2 - la1) * k / n, lo1 + (lo2 - lo1) * k / n) for k in range(1, n + 1)]
    return out


def lonlat_points(line):
    """The drawn points, [lon, lat] at 4 dp, exactly as js_line prints them (both holders share them)."""
    return [[float(f'{lo:.4f}'), float(f'{la:.4f}')] for la, lo in every_km(line)]


def js_line(name, airport, kind, freq, line):
    pts = ', '.join(f'[{lo:.4f}, {la:.4f}]' for la, lo in every_km(line))
    return (
        f'        {{ name: {json.dumps(name)}, airport: {json.dumps(airport)}, type: {json.dumps(kind)}, '
        f'freq: {json.dumps(freq)}, coordinates: [{pts}] }},'
    )


def route_records(f, record):
    """Every Bay Area line, in drawing order: finals, departures, arrivals.

    THE ONE DERIVATION for the two route holders (2026-10-07): the live map's
    BAYAREA-MAP block and data/us-bayarea-routes.json, which the front page
    reads. Until then the front page re-derived its lines from the raw FAA
    record - finals from the thresholds, departures from every waypoint rather
    than the page's first 30 km, and no arrivals at all - so the two maps drew
    different lines for the same airports.
    """
    out = []
    for r in f['approaches']:
        brg = record['airports'][r['airport']]['runways'][r['runway']]['true_brg']
        out.append(
            {
                'kind': 'final',
                'airport': r['airport'],
                'name': f'{r["airport"]} {r["runway"]} final approach',
                'runway': r['runway'],
                'glide_deg': r['glide'],
                'bearing': brg,
                # Stroke width only. The UK builder's rule (a final landing into the west
                # is the busy one) holds here too: the bay's prevailing wind is westerly.
                'freq': 'high' if uk.busy_final(brg) else 'medium',
                # Drawn from 3,000 ft down to the threshold, as the UK finals are.
                'line': r['line'][::-1],
            }
        )
    seen = set()
    for d in f['departures']:
        key = tuple((round(la, 4), round(lo, 4)) for la, lo in d['line'])
        if key in seen:  # two transitions that share their first 30 km are one line
            continue
        seen.add(key)
        out.append(
            {
                'kind': 'departure',
                'airport': d['airport'],
                'name': f'{d["airport"]} departure via {d["name"]}',
                'procedure': d['name'],
                'freq': 'medium',
                'line': d['line'],
            }
        )
    # Arrivals run TOWARDS the airport and end where a final begins (or where
    # the coded route hands over to radar vectors), so the map's 'arrival'
    # rule - hold the END on screen - is the right one for them too.
    for a in f['arrivals']:
        out.append(
            {
                'kind': 'arrival',
                'airport': a['airport'],
                'name': f'{a["airport"]} arrival via {a["name"]}',
                'procedure': a['name'],
                'via': [fix for fix, _, _ in a['fixes']],
                'freq': 'medium',
                'line': a['line'],
            }
        )
    return out


def site_block(routes, record):
    # The cycle the lines are from, for the legend to name. It was typed into
    # the legend by hand, so the next FAA cycle would have redrawn every line
    # here and left the legend naming the old one.
    out = [f'      const BAYAREA_ROUTES_CYCLE = {json.dumps(record["cycle"])};', '      const BAYAREA_AIRPORTS = [']
    for code in page.AIRPORTS:
        lat, lon = record['airports'][code]['ref']
        out.append(
            f'        {{ code: {json.dumps(code)}, name: {json.dumps(page.AIRPORT_NAMES[code])}, '
            f"coords: [{lon:.4f}, {lat:.4f}], type: 'airport' }},"
        )
    out += ['      ];', '      const BAYAREA_FLIGHT_PATHS = [']
    # The live map's dialect has two types: a final is an 'arrival' there.
    for r in routes:
        kind = 'departure' if r['kind'] == 'departure' else 'arrival'
        out.append(js_line(r['name'], r['airport'], kind, r['freq'], r['line']))
    out.append('      ];')
    return '\n'.join(out)


def routes_doc(routes, record):
    """data/us-bayarea-routes.json: the same records as the live map's block, for the front page."""
    keep = ('kind', 'airport', 'name', 'runway', 'glide_deg', 'bearing', 'procedure', 'via')
    return {
        'source': f'FAA CIFP cycle {record["cycle"]}, effective {record["effective"]}',
        'cycle': record['cycle'],
        'generator': 'scripts/build_bayarea_map_data.py --write; the live map draws the same lines (BAYAREA-MAP)',
        'airports': [
            {
                'code': code,
                'name': page.AIRPORT_NAMES[code],
                'ref': [
                    float(f'{record["airports"][code]["ref"][1]:.4f}'),
                    float(f'{record["airports"][code]["ref"][0]:.4f}'),
                ],
            }
            for code in page.AIRPORTS
        ],
        'routes': [{**{k: r[k] for k in keep if k in r}, 'coordinates': lonlat_points(r['line'])} for r in routes],
    }


def render(fc):
    return json.dumps(fc, separators=(',', ':'), ensure_ascii=False) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument('--check', action='store_true')
    g.add_argument('--write', action='store_true')
    args = ap.parse_args()
    fc, f, record = build()
    rings = sum(len(poly) for ft in fc['features'] for poly in ft['geometry']['coordinates'])
    holes = sum(len(poly) - 1 for ft in fc['features'] for poly in ft['geometry']['coordinates'])
    on_map = sum(1 for ft in fc['features'] if ft['properties']['noise'] not in ('None', 'Under 1%'))
    print(
        f'{len(fc["features"])} cities, {rings} rings ({holes} holes grouped), {on_map} at 1% or more on the noise map'
    )
    body = render(fc)
    routes = route_records(f, record)
    block = site_block(routes, record)
    n = Counter(r['kind'] for r in routes)
    print(
        f'{n["final"]} final approaches, {n["arrival"]} arrivals and {n["departure"]} distinct departures, from {fc["routes"]}'
    )
    stale = []
    for path, text in ((OUT, body), (ROUTES_OUT, render(routes_doc(routes, record)))):
        if not path.exists() or path.read_text(encoding='utf-8') != text:
            stale.append(str(path.relative_to(ROOT)))
            if args.write:
                path.write_text(text, encoding='utf-8', newline='\n')
    if uk.replace_block(SITE, START, END, block, args.write):
        stale.append(f'{SITE.name} (BAYAREA-MAP)')
    if args.write:
        print('rewrote ' + ', '.join(stale) if stale else 'all three holders already match')
        return 0
    if stale:
        print('FAIL: stale: ' + ', '.join(stale) + ' - run scripts/build_bayarea_map_data.py --write')
        return 1
    print('PASS: the outlines, the routes file and the index.html block all equal a fresh derivation')
    return 0


if __name__ == '__main__':
    sys.exit(main())
