"""Borough `avgPrice` and `trend` from HM Land Registry UK HPI, keyed on ONS codes.

Why this exists
---------------
Both fields were entered by hand for every city, with no script and no cached
dataset, so nothing in the repo could re-derive them and nothing could notice
when one of them drifted. That is not hypothetical. When this script was first
run on 2026-08-10 it found London's `avgPrice` matching HPI 2026-05 for all 33
boroughs while its `trend` matched **no HPI month at all** - two cities carrying
one provenance sentence from two different sources. The trends were corrected in
the same commit that added this, and `--check` has guarded them since.

WHY ONS CODES AND NOT NAMES
---------------------------
Name matching has failed this project five separate times, and every failure
looked like missing data rather than a spelling difference:

  * `Brentwood` (Essex) matched the London borough key `Brent` and was drawn as
    a London borough, feeding the map projection an outlier 30 km out.
  * `ST. HELENS` in Price Paid did not match a district list, and was recorded
    as Merseyside having only 4 of 5 districts.
  * `VALE OF GLAMORGAN` did not match either - Price Paid calls it
    `THE VALE OF GLAMORGAN`, with the article.
  * `NOTTINGHAM` did not match; Price Paid calls it `CITY OF NOTTINGHAM`.
  * `Westminster` finds no HPI row; HPI calls it `City of Westminster`.

The same place is spelled differently in two datasets from the same department:
Price Paid says `ST. HELENS`, HPI says `St Helens`. A code cannot be spelled
differently. CITY_LADS below was GENERATED by resolving names against the HPI
file once and pinning the result, not typed from memory - which caught that
Barnsley and Sheffield are E08000038 and E08000039, not the E08000016 and
E08000019 they are widely reported as.

Usage
-----
    python scripts/build_hpi_prices.py --check --city london
    python scripts/build_hpi_prices.py --check --all
    python scripts/build_hpi_prices.py --emit --city westmidlands

`--check` compares what the score Lambda holds against HPI and exits non-zero on
drift, so it can sit in preflight. `--emit` prints a paste-ready borough block
for a city that does not exist yet. Re-run `--check` after every HPI release
(monthly); drift is the signal to roll the vintage, not a bug.
"""

from __future__ import annotations

import argparse
import calendar
import csv
import re
import sys
import types
import urllib.request
from pathlib import Path

# The vintage the registry claims, in CITY_PROVENANCE and in CLAUDE.md.
DEFAULT_VINTAGE = "2026-06-01"  # June 2026 UK HPI, rolled 2026-08-25
CACHE = Path("data/hpi-average-prices.csv")
SCORE_APP = Path("backend/lambdas/score/app.py")

# The "Average prices" file, not "UK-HPI-full-file": it carries exactly the two
# fields wanted (Average_Price, Annual_Change) at 7.5 MB rather than the full
# file's 50+ columns. The month in the URL is the vintage's own month.
URL_TEMPLATE = (
    "https://publicdata.landregistry.gov.uk/market-trend-data/"
    "house-price-index-data/Average-prices-{year}-{month}.csv"
)

# City id -> {borough name as the registry holds it: ONS area code}.
# GENERATED, not authored - see the module docstring.
CITY_LADS = {
    "london": {
        "Hounslow": "E09000018",
        "Hillingdon": "E09000017",
        "Richmond upon Thames": "E09000027",
        "Ealing": "E09000009",
        "Wandsworth": "E09000032",
        "Lambeth": "E09000022",
        "Lewisham": "E09000023",
        "Greenwich": "E09000011",
        "Tower Hamlets": "E09000030",
        "Camden": "E09000007",
        "Islington": "E09000019",
        "Hackney": "E09000012",
        "Barnet": "E09000003",
        "Croydon": "E09000008",
        "Bromley": "E09000006",
        "Newham": "E09000025",
        "Southwark": "E09000028",
        "Hammersmith and Fulham": "E09000013",
        "Kensington and Chelsea": "E09000020",
        "Brent": "E09000005",
        "Haringey": "E09000014",
        "Waltham Forest": "E09000031",
        "Merton": "E09000024",
        "Redbridge": "E09000026",
        "Enfield": "E09000010",
        "Kingston upon Thames": "E09000021",
        "Sutton": "E09000029",
        "Westminster": "E09000033",
        "City of London": "E09000001",
        "Barking and Dagenham": "E09000002",
        "Havering": "E09000016",
        "Bexley": "E09000004",
        "Harrow": "E09000015",
    },
    "manchester": {
        "Manchester": "E08000003",
        "Salford": "E08000006",
        "Stockport": "E08000007",
        "Trafford": "E08000009",
        "Tameside": "E08000008",
        "Oldham": "E08000004",
        "Rochdale": "E08000005",
        "Bury": "E08000002",
        "Bolton": "E08000001",
        "Wigan": "E08000010",
    },
    # --- Core Cities not yet in the registry -------------------------------
    # Metropolitan counties are the whole force/county area, so the borough set
    # is unambiguous. The three UNITARY regions below are not: each is one
    # authority on its own, and a one-borough cohort scores afford = 5.0 flat
    # (score/app.py: `if max_price == min_price`), a fabricated middling number.
    # Their neighbours are included for that reason, and the composition is
    # recorded here rather than left implicit.
    "westmidlands": {
        "Birmingham": "E08000025",
        "Coventry": "E08000026",
        "Dudley": "E08000027",
        "Sandwell": "E08000028",
        "Solihull": "E08000029",
        "Walsall": "E08000030",
        "Wolverhampton": "E08000031",
    },
    "westyorkshire": {
        "Bradford": "E08000032",
        "Calderdale": "E08000033",
        "Kirklees": "E08000034",
        "Leeds": "E08000035",
        "Wakefield": "E08000036",
    },
    "southyorkshire": {
        "Barnsley": "E08000038",
        "Doncaster": "E08000017",
        "Rotherham": "E08000018",
        "Sheffield": "E08000039",
    },
    "merseyside": {
        "Knowsley": "E08000011",
        "Liverpool": "E08000012",
        "St Helens": "E08000013",
        "Sefton": "E08000014",
        "Wirral": "E08000015",
    },
    "tyneandwear": {
        "Gateshead": "E08000037",
        "Newcastle upon Tyne": "E08000021",
        "North Tyneside": "E08000022",
        "South Tyneside": "E08000023",
        "Sunderland": "E08000024",
    },
    # West of England. Bristol alone is one authority; Bath and North East
    # Somerset, North Somerset and South Gloucestershire make it a real cohort.
    "bristol": {
        "City of Bristol": "E06000023",
        "Bath and North East Somerset": "E06000022",
        "North Somerset": "E06000024",
        "South Gloucestershire": "E06000025",
    },
    # Greater Nottingham: the city plus the three boroughs of its conurbation.
    "nottingham": {
        "City of Nottingham": "E06000018",
        "Broxtowe": "E07000172",
        "Gedling": "E07000173",
        "Rushcliffe": "E07000176",
    },
    # Leicester and Leicestershire: the city plus all seven county districts.
    # The whole county rather than just the three contiguous boroughs, because a
    # four-authority cohort of Leicester/Blaby/Charnwood/Oadby spans only
    # 230k-281k and min-max scaling over a narrow cohort manufactures spread it
    # has not measured. All eight span 230k-346k, 1.50x.
    "leicester": {
        "Leicester": "E06000016",
        "Blaby": "E07000129",
        "Charnwood": "E07000130",
        "Harborough": "E07000131",
        "Hinckley and Bosworth": "E07000132",
        "Melton": "E07000133",
        "North West Leicestershire": "E07000134",
        "Oadby and Wigston": "E07000135",
    },
    # Teesside: the five Tees Valley unitaries. Darlington is included because
    # it is part of the Tees Valley Combined Authority and its travel-to-work
    # area, not because it is on the river.
    "teesside": {
        "Hartlepool": "E06000001",
        "Middlesbrough": "E06000002",
        "Redcar and Cleveland": "E06000003",
        "Stockton-on-Tees": "E06000004",
        "Darlington": "E06000005",
    },
    # Cardiff spans TWO police forces (South Wales, Gwent), which matters for
    # the crime loader rather than here - noted so the composition is not
    # re-derived differently in two places.
    "cardiff": {
        "Cardiff": "W06000015",
        "Vale of Glamorgan": "W06000014",
        "Newport": "W06000022",
        "Caerphilly": "W06000018",
    },
}

# Cities the score Lambda actually holds, so --check has something to compare
# against. The rest are --emit only until they are added.
#
# DERIVED, not listed. It was a hardcoded ("london", "manchester") pair, and
# eight cities landed in the Lambda while the blocking `prices == HM Land
# Registry` stage went on checking two of them - a gate quietly covering a fifth
# of what it claimed. Reading the Lambda means a city cannot join the registry
# without joining the check.
def _in_registry():
    try:
        return tuple(c for c in registry_cities() if c in CITY_LADS)
    except Exception:  # noqa: BLE001 - fall back rather than break --emit
        return ("london", "manchester")

# Registry prices are rounded to the nearest GBP 1,000 for London and exact for
# Greater Manchester, so an equality test would report drift on 33 boroughs that
# are in fact correct. Half a rounding step is the widest a correctly-rounded
# value can sit from its source.
PRICE_TOLERANCE = 500.0
TREND_TOLERANCE = 0.05


def fetch(vintage: str) -> None:
    """Download the HPI average-prices file for `vintage` if not cached."""
    if CACHE.exists():
        return
    year, month, _ = vintage.split("-")
    url = URL_TEMPLATE.format(year=year, month=month)
    print(f"fetching {url} ...", file=sys.stderr)
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url, timeout=300) as resp:
        CACHE.write_bytes(resp.read())


def load_hpi(vintage: str) -> dict[str, dict]:
    """{area code: {name, price, trend}} for one month of the HPI series."""
    fetch(vintage)
    out: dict[str, dict] = {}
    # utf-8-sig: the file carries a BOM, and without this the first column name
    # reads as '﻿Date' and every row lookup misses.
    with CACHE.open(newline="", encoding="utf-8-sig") as fh:
        for row in csv.DictReader(fh):
            if row["Date"] != vintage:
                continue
            price = row["Average_Price"]
            trend = row["Annual_Change"]
            out[row["Area_Code"].strip()] = {
                "name": row["Region_Name"].strip(),
                "price": float(price) if price else None,
                "trend": round(float(trend), 1) if trend else None,
            }
    if not out:
        raise SystemExit(
            f"No rows dated {vintage} in {CACHE}. The cache may predate the "
            f"vintage - delete it and re-run to refetch."
        )
    return out


def _load_score_app():
    """The score Lambda, compiled from source text - see registry_boroughs."""
    mod = types.ModuleType("score_app_hpi_check")
    mod.__file__ = str(SCORE_APP)
    exec(  # noqa: S102 - first-party file, maintainer-run script, never deployed
        compile(SCORE_APP.read_text(encoding="utf-8"), str(SCORE_APP), "exec"),
        mod.__dict__,
    )
    return mod


def registry_cities():
    """Every city the score Lambda holds."""
    return list(_load_score_app().CITIES)


def registry_boroughs(city: str) -> dict[str, dict]:
    """What the score Lambda holds for `city`.

    Compiled from the SOURCE TEXT rather than imported, for the reason
    scripts/refresh_crime_from_ons.py records at length: importlib honours
    __pycache__, which it validates on the source's size and mtime, so a
    same-length edit restored within one clock second lets Python run bytecode
    compiled from code that no longer exists. Reading the text has no cache.
    """
    return _load_score_app().CITIES[city]["boroughs"]


def check_vintage_words(vintage: str) -> int:
    """The provenance PROSE must name the vintage the numbers came from.

    I2, 2026-08-31. `--check` compared 99 boroughs' avgPrice and trend against
    HPI 2026-06 and passed, while thirty-four provenance strings in the same
    file told integrators the figures were "May 2026 vintage". The June roll
    landed on 2026-08-25 and moved the NUMBERS; the SENTENCES beside them were
    not brought along, and no gate could see it because this one compares
    numbers only.

    That matters more than a stale comment: `terms.html` obliges integrators to
    pass the `sources` array through to their own users, so the wrong vintage is
    republished downstream as a licensing and provenance claim.

    Counted, not merely searched. A rename upstream that leaves ZERO matching
    strings would satisfy "no wrong month found" while describing nothing.
    """
    year, month, _ = vintage.split("-")
    want = f"{calendar.month_name[int(month)]} {year} vintage"
    text = SCORE_APP.read_text(encoding="utf-8")
    found = text.count(want)
    stale = sorted({
        m for m in re.findall(r"([A-Z][a-z]+ 20\d\d vintage)", text) if m != want
    })
    print("")
    print(f"provenance prose: {found} strings say {want!r}")
    if stale:
        print(f"FAIL: {len(stale)} other vintage(s) named in the same file: {', '.join(stale)}")
        print(f"      The numbers are HPI {vintage}. Replace them with {want!r}.")
        return 1
    if not found:
        print(f"FAIL: no provenance string names {want!r}. A vintage nobody states is")
        print("      one an integrator cannot audit, and a zero count is not agreement.")
        return 1
    return 0


def check(city: str, hpi: dict[str, dict], vintage: str) -> int:
    """Compare the registry against HPI. Returns the number of disagreements."""
    lads = CITY_LADS[city]
    held = registry_boroughs(city)

    # A FLOOR, not a courtesy. This is a blocking preflight stage, and until
    # 2026-08-22 an empty block printed "0/0 agree" and returned 0 - the same
    # output shape as a clean run over 33 boroughs. Renaming the marker
    # registry_boroughs() reads is enough to produce it. Audit finding I5's
    # class, in the gate that guards prices.
    if not held:
        print(f"\n{city}: FAIL - the registry holds NO boroughs to compare.")
        print("  Comparing zero fields is not agreement. Check the marker "
              "registry_boroughs() reads in the score Lambda.")
        return 1

    price_bad, trend_bad, missing = [], [], []

    for name, bd in held.items():
        code = lads.get(name)
        if not code:
            missing.append(f"{name}: no ONS code in CITY_LADS")
            continue
        row = hpi.get(code)
        if not row:
            missing.append(f"{name}: no HPI row for {code}")
            continue
        if row["price"] is None or abs(bd["avgPrice"] - row["price"]) > PRICE_TOLERANCE:
            price_bad.append(f"{name}: registry {bd['avgPrice']:,} vs HPI {row['price']:,.0f}")
        if row["trend"] is None or abs(bd["trend"] - row["trend"]) > TREND_TOLERANCE:
            trend_bad.append(f"{name}: registry {bd['trend']}% vs HPI {row['trend']}%")

    total = len(held)
    print(f"\n{city} against HPI {vintage} ({total} boroughs)")
    print(f"  avgPrice  {total - len(price_bad) - len(missing):>3}/{total} agree")
    print(f"  trend     {total - len(trend_bad) - len(missing):>3}/{total} agree")
    for label, rows in (("UNRESOLVED", missing), ("PRICE DRIFT", price_bad), ("TREND DRIFT", trend_bad)):
        for line in rows:
            print(f"    {label}: {line}")
    return len(price_bad) + len(trend_bad) + len(missing)


def emit(city: str, hpi: dict[str, dict]) -> int:
    """Print a paste-ready borough block for a city not yet in the registry."""
    lads = CITY_LADS[city]
    print(f"# {city}: HM Land Registry UK HPI, {len(lads)} authorities.")
    print(f"{city.upper()}_BOROUGHS = {{")
    problems = 0
    for name, code in lads.items():
        row = hpi.get(code)
        if not row or row["price"] is None or row["trend"] is None:
            print(f"    # {name}: NO HPI ROW for {code} - unresolved, do not ship")
            problems += 1
            continue
        print(
            f"    '{name}': {{'avgPrice': {row['price']:.0f}, 'trend': {row['trend']}, "
            f"'p8': None, 'crimeRate': None}},  # {code}"
        )
    print("}")
    if problems:
        print(f"# {problems} authority/authorities unresolved", file=sys.stderr)
    return problems


# `trend` and `avgPrice` live in TWO holders, and unlike the liveability inputs
# nothing enforces that they agree: tests/test_borough_data_parity.py compares
# crimeRate/schools/transport/healthcare/p8 only. So --write must touch both or
# it creates exactly the site/API divergence this repo has shipped three times.
SITE_HOLDER = Path("index.html")
# The site keys this borough differently from the Lambda. Declared, not
# fuzzy-matched, for the reason test_borough_data_parity.py gives: a fuzzy match
# would also quietly pair a genuinely missing borough with a similar one.
SITE_NAME = {"Barking and Dagenham": "Barking"}


def _block_span(text: str, marker: str) -> tuple[int, int]:
    """Character span of the object literal introduced by `marker`.

    Scoping the rewrite to this span is load-bearing, not tidiness. Searching
    the whole file finds the FIRST `Hounslow: {`, which in index.html is a
    different structure entirely - AREA_MAP and the road-noise table both key on
    borough names and both appear before BOROUGH_DATA_RAW. The first attempt at
    this failed on 11 of 33 boroughs for exactly that reason, and the ones it
    did not fail on were the multi-word names that happen to be unique.
    """
    i = text.index(marker)
    open_at = text.index("{", i)
    depth, j = 0, open_at
    while j < len(text):
        if text[j] == "{":
            depth += 1
        elif text[j] == "}":
            depth -= 1
            if depth == 0:
                return open_at, j
        j += 1
    raise SystemExit(f"Unbalanced braces after {marker!r}")


def _rewrite_trend(
    text: str, marker: str, key_pat: str, trend_pat: str, wanted: dict[str, float]
) -> tuple[str, list[str]]:
    """Replace each borough's `trend` in one holder. Returns (text, unapplied)."""
    import re

    lo, hi = _block_span(text, marker)
    unapplied = []
    for name, value in wanted.items():
        key = re.compile(key_pat.format(name=re.escape(name))).search(text, lo, hi)
        if not key:
            unapplied.append(f"{name}: key not found")
            continue
        # Scoped to this borough's own block - search forward from its key only,
        # and only a short way, so a miss cannot silently edit the NEXT
        # borough's trend and report success.
        window = text[key.end() : key.end() + 900]
        m = re.search(trend_pat, window)
        if not m:
            unapplied.append(f"{name}: no trend line within its block")
            continue
        start = key.end() + m.start()
        end = key.end() + m.end()
        text = text[:start] + m.group(0).replace(m.group(1), f"{value}") + text[end:]
    return text, unapplied


def write(city: str, hpi: dict[str, dict]) -> int:
    """Correct `avgPrice` and `trend` from HPI. Returns the number unapplied.

    GENERALISED FROM LONDON-AND-TREND-ONLY ON 2026-08-24, during the first
    vintage roll this repo has performed (2026-05 to 2026-06). The original
    write path was built for the 2026-08-10 incident, where only London's
    trends were wrong - so the first real roll found the tool could correct
    one field of one city while --check rightly failed the other eleven.

    Which holders get written depends on the city, and the asymmetry is the
    point rather than an accident:
      * The LAMBDA dict ({CITY}_BOROUGHS) is written for every city - it is
        the single source the frontend generator reads.
      * London's SITE block is written directly, because London's frontend
        data is hand-curated markup that build_city_frontend_block.py does
        not generate.
      * Every other city's site block must be REGENERATED afterwards with
        `build_city_frontend_block.py --city X --insert` - this function
        prints the reminder, and `tests/borough-score-parity.mjs` fails the
        build if it is forgotten, which is the gate actually guarding the
        two-holder divergence here.
    """
    lads = CITY_LADS[city]
    held = registry_boroughs(city)
    wanted_t = {n: hpi[lads[n]]["trend"] for n in held if lads.get(n) and hpi.get(lads[n])}
    wanted_p = {n: hpi[lads[n]]["price"] for n in held if lads.get(n) and hpi.get(lads[n])}
    changed_t = {n: v for n, v in wanted_t.items() if abs(held[n]["trend"] - v) > TREND_TOLERANCE}
    changed_p = {
        n: v
        for n, v in wanted_p.items()
        if v is not None and abs(held[n]["avgPrice"] - v) > PRICE_TOLERANCE
    }
    if not changed_t and not changed_p:
        print("Nothing to do: every avgPrice and trend already matches HPI.")
        return 0
    print(f"{city}: {len(changed_p)} price(s) and {len(changed_t)} trend(s) need a new value.")

    marker = f"{city.upper()}_BOROUGHS = {{"
    lam = SCORE_APP.read_text(encoding="utf-8")
    lam, bad_t = _rewrite_trend(
        lam, marker, r"'{name}': \{{", r"'trend': (-?\d+\.?\d*)", changed_t
    )
    lam, bad_p = _rewrite_trend(
        lam,
        marker,
        r"'{name}': \{{",
        r"'avgPrice': (\d+)",
        {n: f"{v:.0f}" for n, v in changed_p.items()},
    )

    bad_site_t: list[str] = []
    bad_site_p: list[str] = []
    site = None
    if city == "london":
        site = SITE_HOLDER.read_text(encoding="utf-8")
        site_t = {SITE_NAME.get(n, n): v for n, v in changed_t.items()}
        site_p = {SITE_NAME.get(n, n): f"{v:.0f}" for n, v in changed_p.items()}
        site, bad_site_t = _rewrite_trend(
            site,
            "const BOROUGH_DATA_RAW = {",
            r"'?{name}'?: \{{",
            r"\btrend: (-?\d+\.?\d*)",
            site_t,
        )
        site, bad_site_p = _rewrite_trend(
            site,
            "const BOROUGH_DATA_RAW = {",
            r"'?{name}'?: \{{",
            r"avg_price: (\d+)",
            site_p,
        )

    problems = bad_t + bad_p + bad_site_t + bad_site_p
    if problems:
        # Write NOTHING. A half-applied correction is the divergence this
        # function exists to avoid, and it would be committed looking complete.
        for p in problems:
            print(f"  UNAPPLIED: {p}", file=sys.stderr)
        print("No files written - fix the above and re-run.", file=sys.stderr)
        return len(problems)

    SCORE_APP.write_text(lam, encoding="utf-8", newline="")
    if site is not None:
        SITE_HOLDER.write_text(site, encoding="utf-8", newline="")
        print(f"Wrote {SCORE_APP} and {SITE_HOLDER}. Re-run --check to confirm.")
    else:
        print(
            f"Wrote {SCORE_APP}. Now regenerate the site block: "
            f"python scripts/build_city_frontend_block.py --city {city} --insert"
        )
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--city", choices=sorted(CITY_LADS), help="city to check or emit")
    ap.add_argument("--all", action="store_true", help="check every city already in the registry")
    ap.add_argument("--check", action="store_true", help="compare the registry against HPI")
    ap.add_argument("--emit", action="store_true", help="print a paste-ready borough block")
    ap.add_argument("--write", action="store_true", help="correct `trend` in BOTH holders from HPI")
    ap.add_argument("--vintage", default=DEFAULT_VINTAGE, help=f"HPI month, default {DEFAULT_VINTAGE}")
    args = ap.parse_args()

    if not (args.check or args.emit or args.write):
        ap.error("pass --check, --emit or --write")
    if not args.city and not args.all:
        ap.error("pass --city, or --all with --check")

    hpi = load_hpi(args.vintage)

    if args.write:
        if not args.city:
            ap.error("--write needs --city")
        return 1 if write(args.city, hpi) else 0

    if args.emit:
        if not args.city:
            ap.error("--emit needs --city")
        return 1 if emit(args.city, hpi) else 0

    in_registry = _in_registry()
    cities = in_registry if args.all else (args.city,)
    for city in cities:
        if city not in in_registry:
            print(f"{city} is not in the score Lambda yet - use --emit.", file=sys.stderr)
            return 2
    if not cities:
        print(
            "FAIL: no cities to check. `sum(())` is 0, so this used to print "
            "PASS having compared nothing at all.",
            file=sys.stderr,
        )
        return 1
    bad = sum(check(city, hpi, args.vintage) for city in cities)
    bad += check_vintage_words(args.vintage)
    print(f"\nChecked {len(cities)} city/cities against HPI {args.vintage}.")
    print(f"RESULT: {'PASS' if bad == 0 else f'FAIL ({bad} disagreements)'}")
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
