"""Borough `avgPrice` and `trend` from HM Land Registry UK HPI, keyed on ONS codes.

Why this exists
---------------
Both fields were entered by hand for every city, with no script and no cached
dataset, so nothing in the repo could re-derive them and nothing could notice
when one of them drifted. That is not hypothetical: as of 2026-08-10 London's
`avgPrice` matches HPI 2026-05 for all 33 boroughs while its `trend` matches
**no HPI month at all**, and Greater Manchester's matches 2026-05 for all ten.
Two cities, one provenance sentence in CITY_PROVENANCE, two different sources.

WHY ONS CODES AND NOT NAMES
---------------------------
Name matching has failed this project five separate times, and every failure
looked like missing data rather than a spelling difference:

  * `Brentwood` (Essex) matched the London borough key `Brent` and was drawn as
    a London borough, feeding the map projection an outlier 30 km out.
  * `ST. HELENS` in Price Paid did not match a district list, and was recorded
    as Merseyside having only 4 of 5 districts.
  * `VALE OF GLAMORGAN` did not match either - Price Paid calls it
    `THE VALE OF GLAMORGAN`, with the article.
  * `NOTTINGHAM` did not match; Price Paid calls it `CITY OF NOTTINGHAM`.
  * `Westminster` finds no HPI row; HPI calls it `City of Westminster`.

The same place is spelled differently in two datasets from the same department:
Price Paid says `ST. HELENS`, HPI says `St Helens`. A code cannot be spelled
differently. CITY_LADS below was GENERATED by resolving names against the HPI
file once and pinning the result, not typed from memory - which caught that
Barnsley and Sheffield are E08000038 and E08000039, not the E08000016 and
E08000019 they are widely reported as.

Usage
-----
    python scripts/build_hpi_prices.py --check --city london
    python scripts/build_hpi_prices.py --check --all
    python scripts/build_hpi_prices.py --emit --city westmidlands

`--check` compares what the score Lambda holds against HPI and exits non-zero on
drift, so it can sit in preflight. `--emit` prints a paste-ready borough block
for a city that does not exist yet. Re-run `--check` after every HPI release
(monthly); drift is the signal to roll the vintage, not a bug.
"""

from __future__ import annotations

import argparse
import csv
import sys
import types
import urllib.request
from pathlib import Path

# The vintage the registry claims, in CITY_PROVENANCE and in CLAUDE.md.
DEFAULT_VINTAGE = "2026-05-01"
CACHE = Path("data/hpi-average-prices.csv")
SCORE_APP = Path("backend/lambdas/score/app.py")

# The "Average prices" file, not "UK-HPI-full-file": it carries exactly the two
# fields wanted (Average_Price, Annual_Change) at 7.5 MB rather than the full
# file's 50+ columns. The month in the URL is the vintage's own month.
URL_TEMPLATE = (
    "https://publicdata.landregistry.gov.uk/market-trend-data/"
    "house-price-index-data/Average-prices-{year}-{month}.csv"
)

# City id -> {borough name as the registry holds it: ONS area code}.
# GENERATED, not authored - see the module docstring.
CITY_LADS = {
    "london": {
        "Hounslow": "E09000018",
        "Hillingdon": "E09000017",
        "Richmond upon Thames": "E09000027",
        "Ealing": "E09000009",
        "Wandsworth": "E09000032",
        "Lambeth": "E09000022",
        "Lewisham": "E09000023",
        "Greenwich": "E09000011",
        "Tower Hamlets": "E09000030",
        "Camden": "E09000007",
        "Islington": "E09000019",
        "Hackney": "E09000012",
        "Barnet": "E09000003",
        "Croydon": "E09000008",
        "Bromley": "E09000006",
        "Newham": "E09000025",
        "Southwark": "E09000028",
        "Hammersmith and Fulham": "E09000013",
        "Kensington and Chelsea": "E09000020",
        "Brent": "E09000005",
        "Haringey": "E09000014",
        "Waltham Forest": "E09000031",
        "Merton": "E09000024",
        "Redbridge": "E09000026",
        "Enfield": "E09000010",
        "Kingston upon Thames": "E09000021",
        "Sutton": "E09000029",
        "Westminster": "E09000033",
        "City of London": "E09000001",
        "Barking and Dagenham": "E09000002",
        "Havering": "E09000016",
        "Bexley": "E09000004",
        "Harrow": "E09000015",
    },
    "manchester": {
        "Manchester": "E08000003",
        "Salford": "E08000006",
        "Stockport": "E08000007",
        "Trafford": "E08000009",
        "Tameside": "E08000008",
        "Oldham": "E08000004",
        "Rochdale": "E08000005",
        "Bury": "E08000002",
        "Bolton": "E08000001",
        "Wigan": "E08000010",
    },
    # --- Core Cities not yet in the registry -------------------------------
    # Metropolitan counties are the whole force/county area, so the borough set
    # is unambiguous. The three UNITARY regions below are not: each is one
    # authority on its own, and a one-borough cohort scores afford = 5.0 flat
    # (score/app.py: `if max_price == min_price`), a fabricated middling number.
    # Their neighbours are included for that reason, and the composition is
    # recorded here rather than left implicit.
    "westmidlands": {
        "Birmingham": "E08000025",
        "Coventry": "E08000026",
        "Dudley": "E08000027",
        "Sandwell": "E08000028",
        "Solihull": "E08000029",
        "Walsall": "E08000030",
        "Wolverhampton": "E08000031",
    },
    "westyorkshire": {
        "Bradford": "E08000032",
        "Calderdale": "E08000033",
        "Kirklees": "E08000034",
        "Leeds": "E08000035",
        "Wakefield": "E08000036",
    },
    "southyorkshire": {
        "Barnsley": "E08000038",
        "Doncaster": "E08000017",
        "Rotherham": "E08000018",
        "Sheffield": "E08000039",
    },
    "merseyside": {
        "Knowsley": "E08000011",
        "Liverpool": "E08000012",
        "St Helens": "E08000013",
        "Sefton": "E08000014",
        "Wirral": "E08000015",
    },
    "tyneandwear": {
        "Gateshead": "E08000037",
        "Newcastle upon Tyne": "E08000021",
        "North Tyneside": "E08000022",
        "South Tyneside": "E08000023",
        "Sunderland": "E08000024",
    },
    # West of England. Bristol alone is one authority; Bath and North East
    # Somerset, North Somerset and South Gloucestershire make it a real cohort.
    "bristol": {
        "City of Bristol": "E06000023",
        "Bath and North East Somerset": "E06000022",
        "North Somerset": "E06000024",
        "South Gloucestershire": "E06000025",
    },
    # Greater Nottingham: the city plus the three boroughs of its conurbation.
    "nottingham": {
        "City of Nottingham": "E06000018",
        "Broxtowe": "E07000172",
        "Gedling": "E07000173",
        "Rushcliffe": "E07000176",
    },
    # Cardiff spans TWO police forces (South Wales, Gwent), which matters for
    # the crime loader rather than here - noted so the composition is not
    # re-derived differently in two places.
    "cardiff": {
        "Cardiff": "W06000015",
        "Vale of Glamorgan": "W06000014",
        "Newport": "W06000022",
        "Caerphilly": "W06000018",
    },
}

# Cities the score Lambda actually holds, so --check has something to compare
# against. The rest are --emit only until they are added.
IN_REGISTRY = ("london", "manchester")

# Registry prices are rounded to the nearest GBP 1,000 for London and exact for
# Greater Manchester, so an equality test would report drift on 33 boroughs that
# are in fact correct. Half a rounding step is the widest a correctly-rounded
# value can sit from its source.
PRICE_TOLERANCE = 500.0
TREND_TOLERANCE = 0.05


def fetch(vintage: str) -> None:
    """Download the HPI average-prices file for `vintage` if not cached."""
    if CACHE.exists():
        return
    year, month, _ = vintage.split("-")
    url = URL_TEMPLATE.format(year=year, month=month)
    print(f"fetching {url} ...", file=sys.stderr)
    CACHE.parent.mkdir(parents=True, exist_ok=True)
    with urllib.request.urlopen(url, timeout=300) as resp:
        CACHE.write_bytes(resp.read())


def load_hpi(vintage: str) -> dict[str, dict]:
    """{area code: {name, price, trend}} for one month of the HPI series."""
    fetch(vintage)
    out: dict[str, dict] = {}
    # utf-8-sig: the file carries a BOM, and without this the first column name
    # reads as '﻿Date' and every row lookup misses.
    with CACHE.open(newline="", encoding="utf-8-sig") as fh:
        for row in csv.DictReader(fh):
            if row["Date"] != vintage:
                continue
            price = row["Average_Price"]
            trend = row["Annual_Change"]
            out[row["Area_Code"].strip()] = {
                "name": row["Region_Name"].strip(),
                "price": float(price) if price else None,
                "trend": round(float(trend), 1) if trend else None,
            }
    if not out:
        raise SystemExit(
            f"No rows dated {vintage} in {CACHE}. The cache may predate the "
            f"vintage - delete it and re-run to refetch."
        )
    return out


def registry_boroughs(city: str) -> dict[str, dict]:
    """What the score Lambda holds for `city`.

    Compiled from the SOURCE TEXT rather than imported, for the reason
    scripts/refresh_crime_from_ons.py records at length: importlib honours
    __pycache__, which it validates on the source's size and mtime, so a
    same-length edit restored within one clock second lets Python run bytecode
    compiled from code that no longer exists. Reading the text has no cache.
    """
    mod = types.ModuleType("score_app_hpi_check")
    mod.__file__ = str(SCORE_APP)
    exec(  # noqa: S102 - first-party file, maintainer-run script, never deployed
        compile(SCORE_APP.read_text(encoding="utf-8"), str(SCORE_APP), "exec"),
        mod.__dict__,
    )
    return mod.CITIES[city]["boroughs"]


def check(city: str, hpi: dict[str, dict], vintage: str) -> int:
    """Compare the registry against HPI. Returns the number of disagreements."""
    lads = CITY_LADS[city]
    held = registry_boroughs(city)
    price_bad, trend_bad, missing = [], [], []

    for name, bd in held.items():
        code = lads.get(name)
        if not code:
            missing.append(f"{name}: no ONS code in CITY_LADS")
            continue
        row = hpi.get(code)
        if not row:
            missing.append(f"{name}: no HPI row for {code}")
            continue
        if row["price"] is None or abs(bd["avgPrice"] - row["price"]) > PRICE_TOLERANCE:
            price_bad.append(f"{name}: registry {bd['avgPrice']:,} vs HPI {row['price']:,.0f}")
        if row["trend"] is None or abs(bd["trend"] - row["trend"]) > TREND_TOLERANCE:
            trend_bad.append(f"{name}: registry {bd['trend']}% vs HPI {row['trend']}%")

    total = len(held)
    print(f"\n{city} against HPI {vintage} ({total} boroughs)")
    print(f"  avgPrice  {total - len(price_bad) - len(missing):>3}/{total} agree")
    print(f"  trend     {total - len(trend_bad) - len(missing):>3}/{total} agree")
    for label, rows in (("UNRESOLVED", missing), ("PRICE DRIFT", price_bad), ("TREND DRIFT", trend_bad)):
        for line in rows:
            print(f"    {label}: {line}")
    return len(price_bad) + len(trend_bad) + len(missing)


def emit(city: str, hpi: dict[str, dict]) -> int:
    """Print a paste-ready borough block for a city not yet in the registry."""
    lads = CITY_LADS[city]
    print(f"# {city}: HM Land Registry UK HPI, {len(lads)} authorities.")
    print(f"{city.upper()}_BOROUGHS = {{")
    problems = 0
    for name, code in lads.items():
        row = hpi.get(code)
        if not row or row["price"] is None or row["trend"] is None:
            print(f"    # {name}: NO HPI ROW for {code} - unresolved, do not ship")
            problems += 1
            continue
        print(
            f"    '{name}': {{'avgPrice': {row['price']:.0f}, 'trend': {row['trend']}, "
            f"'p8': None, 'crimeRate': None}},  # {code}"
        )
    print("}")
    if problems:
        print(f"# {problems} authority/authorities unresolved", file=sys.stderr)
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--city", choices=sorted(CITY_LADS), help="city to check or emit")
    ap.add_argument("--all", action="store_true", help="check every city already in the registry")
    ap.add_argument("--check", action="store_true", help="compare the registry against HPI")
    ap.add_argument("--emit", action="store_true", help="print a paste-ready borough block")
    ap.add_argument("--vintage", default=DEFAULT_VINTAGE, help=f"HPI month, default {DEFAULT_VINTAGE}")
    args = ap.parse_args()

    if not (args.check or args.emit):
        ap.error("pass --check or --emit")
    if not args.city and not args.all:
        ap.error("pass --city, or --all with --check")

    hpi = load_hpi(args.vintage)

    if args.emit:
        if not args.city:
            ap.error("--emit needs --city")
        return 1 if emit(args.city, hpi) else 0

    cities = IN_REGISTRY if args.all else (args.city,)
    for city in cities:
        if city not in IN_REGISTRY:
            print(f"{city} is not in the score Lambda yet - use --emit.", file=sys.stderr)
            return 2
    bad = sum(check(city, hpi, args.vintage) for city in cities)
    print(f"\nRESULT: {'PASS' if bad == 0 else f'FAIL ({bad} disagreements)'}")
    return 0 if bad == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
