"""Paint DEFRA's aircraft-noise map for every city it covers, not London alone.

WHY THIS EXISTS
---------------
London's aircraft layer is a self-hosted PNG rendered once from DEFRA's WMS
(`scripts/refresh_aircraft_noise.sh`). No other city had one, so their maps
showed only corridor lines, and a Reddit reader said so on 2026-09-25: "No data
for Manchester other than the approach lines". The data existed all along:
DEFRA's single `Airport_Noise_ALL_Lden` layer maps every English airport in
Round 4, and seven of those rasters were already loaded for SCORING. They were
simply never PAINTED.

This renders the same layer over each covered city's own box - the city's
boundary plus its airport, which often sits outside it (Bristol, East
Midlands) - into `data/aircraft-noise-<city>-lden.png`, records each box in the
checked-in `data/aircraft-noise-rasters.json`, and generates the site's
`AIRCRAFT_RASTERS` table from it between markers, so the box the PNG was
rendered for and the box the page positions it at cannot drift apart.

NOT COVERED, by name: Teesside (Round 4 does not map Teesside International),
South Yorkshire (no airport), Cardiff and Nottingham (the site does not render
them), New York (BTS tiles, its own branch). London keeps its existing PNG and
box (`LONDON_AIRCRAFT_BBOX`), which this file references but never refetches.

A BLANK RENDER IS REFUSED. A WMS answers 200 with a transparent image when the
box holds nothing or the layer name drifts, and a transparent PNG would be
positioned, marked loaded, and advertised under a decibel scale. `--fetch`
fails any city whose image paints no pixels; `--check` re-reads each PNG.

Usage
-----
    python scripts/build_aircraft_rasters.py --fetch   # network: DEFRA WMS -> PNGs + JSON
    python scripts/build_aircraft_rasters.py --write   # offline: JSON -> index.html block
    python scripts/build_aircraft_rasters.py --check   # offline, blocking: block == JSON, PNGs painted
"""

from __future__ import annotations

import argparse
import io
import json
import re
import sys
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SITE = ROOT / 'index.html'
LAMBDA = ROOT / 'backend' / 'lambdas' / 'score' / 'app.py'
META = ROOT / 'data' / 'aircraft-noise-rasters.json'

WMS_URL = 'https://environment.data.gov.uk/spatialdata/airport-noise-all-metrics-england-round-4/wms'
LAYER = 'Airport_Noise_ALL_Lden'
UA = {'User-Agent': 'Mozilla/5.0'}  # the host 403s a bare client, like the other DEFRA services
WIDTH = 2048
# Degrees of margin around the airport, so its whole contour strip fits (the
# longest Round 4 contour is East Midlands' 21 km); and around the union box.
AIRPORT_MARGIN_DEG = 0.18
PAD_DEG = 0.03
# A painted pixel is any pixel with alpha above this; the WMS antialiases edges.
ALPHA_FLOOR = 8

# Site cities whose airport DEFRA Round 4 maps. The airport list is the score
# Lambda's AIRPORTS_<CITY>, read from source so it cannot be retyped wrong.
CITIES = ['manchester', 'westmidlands', 'westyorkshire', 'merseyside', 'tyneandwear', 'bristol', 'leicester']
START = '// AIRCRAFT-RASTERS:START (generated by scripts/build_aircraft_rasters.py --write; do not hand-edit)'
END = '// AIRCRAFT-RASTERS:END'


def airports(city):
    src = LAMBDA.read_text(encoding='utf-8')
    i = src.index(f'AIRPORTS_{city.upper()} = [')
    j = src.index('\n]\n', i)
    pts = [(float(a), float(b)) for a, b in re.findall(r"'lat':\s*(-?[\d.]+),\s*'lon':\s*(-?[\d.]+)", src[i:j])]
    if not pts:
        raise SystemExit(f'no airport coordinates found in AIRPORTS_{city.upper()}')
    return pts


def boundary_box(city):
    gj = json.loads((ROOT / 'data' / f'{city}-boroughs.json').read_text(encoding='utf-8'))
    xs, ys = [], []

    def walk(c):
        if isinstance(c[0], (int, float)):
            xs.append(c[0])
            ys.append(c[1])
        else:
            for k in c:
                walk(k)

    for f in gj['features']:
        walk(f['geometry']['coordinates'])
    return min(ys), min(xs), max(ys), max(xs)


def city_box(city):
    la0, lo0, la1, lo1 = boundary_box(city)
    for la, lo in airports(city):
        la0, lo0 = min(la0, la - AIRPORT_MARGIN_DEG), min(lo0, lo - AIRPORT_MARGIN_DEG * 1.6)
        la1, lo1 = max(la1, la + AIRPORT_MARGIN_DEG), max(lo1, lo + AIRPORT_MARGIN_DEG * 1.6)
    return {
        'minLat': round(la0 - PAD_DEG, 2), 'minLon': round(lo0 - PAD_DEG, 2),
        'maxLat': round(la1 + PAD_DEG, 2), 'maxLon': round(lo1 + PAD_DEG, 2),
    }


def painted_share(png_bytes):
    from PIL import Image

    im = Image.open(io.BytesIO(png_bytes)).convert('RGBA')
    alpha = im.getchannel('A')
    hist = alpha.histogram()
    painted = sum(hist[ALPHA_FLOOR + 1:])
    return painted / (im.width * im.height), im.width, im.height


def drop_cut_fragments(png_bytes, bbox, own_airports):
    """Remove painted regions the rendering box CUT that are not this city's.

    The WMS layer holds every airport, so a box drawn round Manchester also
    catches the eastern tip of Liverpool's contour, sliced square by the frame.
    On the map that reads as a glitch - a rectangle of colour floating off the
    city's edge. A region is dropped only if it touches the image border AND
    comes nowhere near one of this city's airports; a whole contour inside the
    box, from any airport, is kept, because it is DEFRA's data and not cut.
    Returns (png bytes, number of regions dropped)."""
    import numpy as np
    from PIL import Image
    from scipy import ndimage

    im = Image.open(io.BytesIO(png_bytes)).convert('RGBA')
    arr = np.array(im)
    mask = arr[:, :, 3] > ALPHA_FLOOR
    labels, n = ndimage.label(mask, structure=np.ones((3, 3)))
    h, w = mask.shape
    edge = set(np.unique(np.concatenate([labels[0], labels[-1], labels[:, 0], labels[:, -1]]))) - {0}

    def px(la, lo):
        x = (lo - bbox['minLon']) / (bbox['maxLon'] - bbox['minLon']) * w
        y = (bbox['maxLat'] - la) / (bbox['maxLat'] - bbox['minLat']) * h
        return x, y

    # Pixel windows round each own airport: a region reaching one is ours.
    near = np.zeros_like(mask)
    for la, lo in own_airports:
        x, y = px(la, lo)
        rx = AIRPORT_MARGIN_DEG * 1.6 / (bbox['maxLon'] - bbox['minLon']) * w
        ry = AIRPORT_MARGIN_DEG / (bbox['maxLat'] - bbox['minLat']) * h
        near[max(0, int(y - ry)):int(y + ry), max(0, int(x - rx)):int(x + rx)] = True
    own = set(np.unique(labels[near & mask])) - {0}
    drop = sorted(edge - own)
    if drop:
        arr[np.isin(labels, drop), 3] = 0
    out = io.BytesIO()
    Image.fromarray(arr).save(out, format='PNG', optimize=True)
    return out.getvalue(), len(drop)


def do_fetch():
    meta = {'source': f'{WMS_URL} layer {LAYER} (DEFRA strategic noise mapping Round 4, 2021 traffic)',
            'generator': 'scripts/build_aircraft_rasters.py --fetch', 'cities': {}}
    for city in CITIES:
        b = city_box(city)
        height = round(WIDTH * (b['maxLat'] - b['minLat']) / (b['maxLon'] - b['minLon']))
        url = (f'{WMS_URL}?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&LAYERS={LAYER}&STYLES=&CRS=EPSG:4326'
               f"&BBOX={b['minLat']},{b['minLon']},{b['maxLat']},{b['maxLon']}"
               f'&WIDTH={WIDTH}&HEIGHT={height}&FORMAT=image/png&TRANSPARENT=true')
        with urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=120) as r:
            body = r.read()
            ctype = r.headers.get('Content-Type', '')
        if 'png' not in ctype:
            raise SystemExit(f'{city}: WMS answered {ctype!r}, not a PNG: {body[:200]!r}')
        if painted_share(body)[0] <= 0:
            raise SystemExit(f'{city}: the render paints NO pixels - refusing a blank surface')
        body, dropped = drop_cut_fragments(body, b, airports(city))
        share, w, h = painted_share(body)
        if share <= 0:
            raise SystemExit(f'{city}: nothing left after dropping cut fragments - the own-airport test is wrong')
        if dropped:
            print(f'{city:14} dropped {dropped} region(s) cut by the box edge that are not its own airport')
        out = ROOT / 'data' / f'aircraft-noise-{city}-lden.png'
        out.write_bytes(body)
        meta['cities'][city] = {'png': f'/data/{out.name}', 'bbox': b, 'px': [w, h],
                                'paintedShare': round(share, 4), 'bytes': len(body)}
        print(f'{city:14} {w}x{h}  painted {share:.2%}  {len(body) / 1024:.0f} KB  bbox {b}')
    META.write_text(json.dumps(meta, indent=1) + '\n', encoding='utf-8', newline='\n')
    print(f'wrote {META.relative_to(ROOT)}')


def render_block(meta):
    lines = ['      const AIRCRAFT_RASTERS = {',
             "        london: { url: '/data/aircraft-noise-london-lden.png', bbox: LONDON_AIRCRAFT_BBOX },"]
    for city, m in meta['cities'].items():
        b = m['bbox']
        lines.append(f"        {city}: {{ url: '{m['png']}', bbox: {{ minLon: {b['minLon']}, maxLon: {b['maxLon']}, "
                     f"minLat: {b['minLat']}, maxLat: {b['maxLat']} }} }},")
    lines.append('      };')
    return '\n'.join(lines)


def do_check_or_write(write):
    if not META.exists():
        raise SystemExit(f'{META.relative_to(ROOT)} missing - run --fetch (network) first')
    meta = json.loads(META.read_text(encoding='utf-8'))
    if set(meta['cities']) != set(CITIES):
        raise SystemExit(f'{META.name} covers {sorted(meta["cities"])}, CITIES is {sorted(CITIES)}')
    bad = []
    for city, m in meta['cities'].items():
        png = ROOT / m['png'].lstrip('/')
        if not png.exists():
            bad.append(f'{city}: {png.name} missing')
            continue
        share, w, h = painted_share(png.read_bytes())
        if share <= 0:
            bad.append(f'{city}: {png.name} paints no pixels')
        elif [w, h] != m['px']:
            bad.append(f'{city}: {png.name} is {w}x{h}, recorded {m["px"]}')
    if bad:
        print('FAIL:\n  ' + '\n  '.join(bad))
        return 1
    src = SITE.read_text(encoding='utf-8')
    crlf = '\r\n' in src
    text = src.replace('\r\n', '\n')
    i, j = text.find(START.split(' (')[0]), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit('index.html: AIRCRAFT-RASTERS markers not found')
    ls = text.rfind('\n', 0, i) + 1
    new = f'      {START}\n{render_block(meta)}\n      {END}'
    old = text[ls: j + len(END)]
    print(f'{len(meta["cities"])} city rasters, every PNG present and painted')
    if old == new:
        print('index.html AIRCRAFT_RASTERS matches data/aircraft-noise-rasters.json')
        return 0
    if not write:
        print('STALE: index.html AIRCRAFT_RASTERS - run scripts/build_aircraft_rasters.py --write')
        return 1
    out = text[:ls] + new + text[j + len(END):]
    SITE.write_text(out.replace('\n', '\r\n') if crlf else out, encoding='utf-8', newline='')
    print('rewrote index.html AIRCRAFT_RASTERS')
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    g = ap.add_mutually_exclusive_group(required=True)
    g.add_argument('--fetch', action='store_true')
    g.add_argument('--write', action='store_true')
    g.add_argument('--check', action='store_true')
    a = ap.parse_args()
    if a.fetch:
        do_fetch()
        return 0
    return do_check_or_write(a.write)


if __name__ == '__main__':
    sys.exit(main())
