name: Deploy Frontend

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - run: aws s3 cp index.html s3://london-flight-map-frontend/index.html --content-type "text/html"
      - run: aws cloudfront create-invalidation --distribution-id EGSSPJKLFL33M --paths "/*"
